import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { mkdir, unlink, writeFile } from 'node:fs/promises';
import { dirname, join, normalize, resolve, sep } from 'node:path';
import type { StorageProvider, StoredObject } from '../storage-provider';

/**
 * Disk-backed storage, served by the API itself.
 *
 * The point of it is that uploads work on a laptop with no cloud account, so
 * "add a product image" is not gated on AWS credentials. It is a real
 * implementation, not a stub — the same validation, the same keys, the same
 * URLs — which is what makes swapping in S3 a configuration change.
 *
 * It is deliberately not the right answer for a multi-instance deployment:
 * files land on one container's filesystem, so a second replica cannot serve
 * them and a restart of an ephemeral container loses them. DEPLOYMENT.md says
 * so, and `isConfigured()` does not pretend otherwise — configure S3 in
 * production.
 */
@Injectable()
export class LocalStorageProvider implements StorageProvider {
  readonly name = 'LOCAL';
  private readonly logger = new Logger(LocalStorageProvider.name);

  constructor(private readonly config: ConfigService) {}

  /** The directory uploads are written to, absolute. */
  get root(): string {
    return resolve(this.config.get<string>('storage.localDir') ?? './uploads');
  }

  /**
   * Where those files are reachable from a browser.
   *
   * Falls back to this API's own address rather than to an empty string. A
   * relative `/uploads/…` would look right in the database and 404 in every
   * browser, because the storefront is served from a different origin than the
   * API that holds the file.
   */
  private get publicBase(): string {
    const configured = this.config.get<string>('storage.publicBaseUrl');
    const base = configured || `http://localhost:${this.config.get<number>('port', 4000)}`;
    return base.replace(/\/+$/, '');
  }

  isConfigured(): boolean {
    // Always available: a filesystem is not something that can be missing.
    return true;
  }

  async put(input: { key: string; body: Buffer; contentType: string }): Promise<StoredObject> {
    const path = this.resolveWithin(input.key);

    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, input.body);

    return {
      key: input.key,
      url: `${this.publicBase}/uploads/${input.key}`,
      bytes: input.body.byteLength,
      contentType: input.contentType,
    };
  }

  async remove(key: string): Promise<void> {
    try {
      await unlink(this.resolveWithin(key));
    } catch (error) {
      const code = (error as NodeJS.ErrnoException).code;
      // Already gone is the desired end state, not a failure.
      if (code !== 'ENOENT') {
        this.logger.warn(`Could not delete ${key}: ${(error as Error).message}`);
      }
    }
  }

  /**
   * Joins a key onto the upload root and refuses anything that escapes it.
   *
   * Keys are generated by MediaService and never taken from a filename, so this
   * should be unreachable — which is exactly why it is here. A path traversal
   * that only one caller prevents is one refactor away from being a way to
   * overwrite arbitrary files as the API process.
   */
  private resolveWithin(key: string): string {
    const root = this.root;
    const path = resolve(join(root, normalize(key)));

    if (path !== root && !path.startsWith(root + sep)) {
      throw new Error(`Refusing to write outside the upload directory: ${key}`);
    }

    return path;
  }
}
